# Generated by Django 6.0 on 2025-12-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Остаток данного вида бутылочек (штук)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bottletype')),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Остаток поштучно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cosmeticproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_bottles', models.PositiveIntegerField(default=0, help_text='Поступившие полные флаконы')),
                ('bottles_left', models.PositiveIntegerField(default=0, help_text='Остаток полных флаконов (целых)')),
                ('ml_left', models.FloatField(default=0.0, help_text='Остаток в мл во вскрытых флаконах (распив)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.perfume')),
            ],
        ),
    ]
