# Generated by Django 6.0 on 2025-12-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_alter_bottletype_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottlestock',
            options={'verbose_name': 'Остаток тары', 'verbose_name_plural': 'Остатки тары'},
        ),
        migrations.AlterModelOptions(
            name='cosmeticstock',
            options={'verbose_name': 'Остаток косметики', 'verbose_name_plural': 'Остатки косметики'},
        ),
        migrations.AlterModelOptions(
            name='perfumestock',
            options={'verbose_name': 'Остаток парфюма', 'verbose_name_plural': 'Остатки парфюма'},
        ),
        migrations.AlterField(
            model_name='bottlestock',
            name='bottle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bottletype', verbose_name='Тип тары'),
        ),
        migrations.AlterField(
            model_name='bottlestock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='bottlestock',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Остаток данного вида бутылочек (штук)', verbose_name='Остаток (шт)'),
        ),
        migrations.AlterField(
            model_name='bottlestock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='cosmeticstock',
            name='cosmetic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cosmeticproduct', verbose_name='Косметика'),
        ),
        migrations.AlterField(
            model_name='cosmeticstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='cosmeticstock',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Остаток поштучно', verbose_name='Остаток (шт)'),
        ),
        migrations.AlterField(
            model_name='cosmeticstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='perfumestock',
            name='bottles_left',
            field=models.PositiveIntegerField(default=0, help_text='Остаток полных флаконов (целых)', verbose_name='Остаток флаконов'),
        ),
        migrations.AlterField(
            model_name='perfumestock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='perfumestock',
            name='ml_left',
            field=models.FloatField(default=0.0, help_text='Остаток в мл во вскрытых флаконах (распив)', verbose_name='Остаток (мл)'),
        ),
        migrations.AlterField(
            model_name='perfumestock',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.perfume', verbose_name='Парфюм'),
        ),
        migrations.AlterField(
            model_name='perfumestock',
            name='received_bottles',
            field=models.PositiveIntegerField(default=0, help_text='Поступившие полные флаконы', verbose_name='Поступило (флаконы)'),
        ),
        migrations.AlterField(
            model_name='perfumestock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
