# Generated by Django 6.0 on 2025-12-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(help_text='Сумма расхода, сом')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(help_text='Сумма дохода, сом')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveIntegerField(default=0, help_text='Скидка на чек (сом)')),
                ('total', models.PositiveIntegerField(default=0, help_text='Итоговая сумма чека, сом')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('full', 'Флакон полностью'), ('split', 'Распив'), ('cosmetic', 'Косметика')], max_length=10)),
                ('bottles_count', models.PositiveIntegerField(default=0, help_text='Флаконов (для продажи целиком)')),
                ('ml', models.FloatField(default=0, help_text='Количество мл (для распива)')),
                ('bottle_count', models.PositiveIntegerField(default=0, help_text='Тара на распив (шт)')),
                ('unit_price', models.PositiveIntegerField(help_text='Цена за 1 мл или 1 ед.')),
                ('discount', models.PositiveIntegerField(default=0, help_text='Скидка на продукт (сом)')),
                ('line_total', models.PositiveIntegerField(help_text='Сумма позиции, сом')),
                ('bottle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.bottletype')),
                ('cosmetic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cosmeticproduct')),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.perfume')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
