# Generated by Django 6.0 on 2025-12-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_bottletype_options_alter_brand_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Доход', 'verbose_name_plural': 'Доходы'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Позиция в чеке', 'verbose_name_plural': 'Позиции в чеке'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(help_text='Сумма расхода, сом', verbose_name='Сумма (сом)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата расхода'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.PositiveIntegerField(help_text='Сумма дохода, сом', verbose_name='Сумма (сом)'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата дохода'),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Скидка на чек (сом)', verbose_name='Скидка на чек (сом)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveIntegerField(default=0, help_text='Итоговая сумма чека, сом', verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='bottle_count',
            field=models.PositiveIntegerField(default=0, help_text='Тара на распив (шт)', verbose_name='Количество тары (шт)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='bottle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.bottletype', verbose_name='Тип тары'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='bottles_count',
            field=models.PositiveIntegerField(default=0, help_text='Флаконов (для продажи целиком)', verbose_name='Количество флаконов'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cosmetic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cosmeticproduct', verbose_name='Косметика'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Скидка на продукт (сом)', verbose_name='Скидка на товар (сом)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='line_total',
            field=models.PositiveIntegerField(help_text='Сумма позиции, сом', verbose_name='Сумма строки'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='ml',
            field=models.FloatField(default=0, help_text='Количество мл (для распива)', verbose_name='Количество (мл)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='perfume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.perfume', verbose_name='Парфюм'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_type',
            field=models.CharField(choices=[('full', 'Флакон полностью'), ('split', 'Распив'), ('cosmetic', 'Косметика')], max_length=10, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.PositiveIntegerField(help_text='Цена за 1 мл или 1 ед.', verbose_name='Цена за ед./мл'),
        ),
    ]
