# Generated by Django 6.0 on 2025-12-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume_ml', models.PositiveIntegerField(help_text='Объем в мл')),
                ('is_paid', models.BooleanField(default=False, help_text='Платная или бесплатная тара')),
                ('price', models.PositiveIntegerField(default=0, help_text='Цена за флакон (если платный)')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit_price', models.PositiveIntegerField(help_text='Цена за штуку, сом')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Остаток на складе, шт')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bottle_volume_ml', models.PositiveIntegerField(help_text='Объем оригинального флакона в мл')),
                ('full_bottle_price', models.PositiveIntegerField(help_text='Цена за полный флакон, сом')),
                ('price_per_ml', models.PositiveIntegerField(help_text='Цена за 1 мл, сом')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='products.brand')),
            ],
        ),
    ]
