# Generated by Django 6.0 on 2025-12-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottletype',
            options={'verbose_name': 'Тип тары', 'verbose_name_plural': 'Типы тары'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='cosmeticproduct',
            options={'verbose_name': 'Косметика', 'verbose_name_plural': 'Косметика'},
        ),
        migrations.AlterModelOptions(
            name='perfume',
            options={'verbose_name': 'Парфюм', 'verbose_name_plural': 'Парфюмы'},
        ),
        migrations.AlterField(
            model_name='bottletype',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Платная или бесплатная тара', verbose_name='Платная тара'),
        ),
        migrations.AlterField(
            model_name='bottletype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название тары'),
        ),
        migrations.AlterField(
            model_name='bottletype',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Цена за флакон (если платный)', verbose_name='Цена (сом)'),
        ),
        migrations.AlterField(
            model_name='bottletype',
            name='volume_ml',
            field=models.PositiveIntegerField(help_text='Объем в мл', verbose_name='Объем (мл)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cosmeticproduct',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='cosmeticproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='products.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cosmeticproduct',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cosmeticproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Остаток на складе, шт', verbose_name='Остаток (шт)'),
        ),
        migrations.AlterField(
            model_name='cosmeticproduct',
            name='unit_price',
            field=models.PositiveIntegerField(help_text='Цена за штуку, сом', verbose_name='Цена (сом)'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='bottle_volume_ml',
            field=models.PositiveIntegerField(help_text='Объем оригинального флакона в мл', verbose_name='Объем флакона (мл)'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='products.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='full_bottle_price',
            field=models.PositiveIntegerField(help_text='Цена за полный флакон, сом', verbose_name='Цена за флакон'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price_per_ml',
            field=models.PositiveIntegerField(help_text='Цена за 1 мл, сом', verbose_name='Цена за 1 мл'),
        ),
    ]
